# Generated by Django 3.0.7 on 2020-06-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200620_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': []},
        ),
    ]
